Update control-room.yml
fixing robot ID

diff --git a/.github/workflows/control-room.yml b/.github/workflows/control-room.yml
--- a/.github/workflows/control-room.yml
+++ b/.github/workflows/control-room.yml
@@ -53,21 +53,16 @@ jobs:
           ROBOCLOUD_API_KEY: ${{ secrets.ROBOCORP_API_KEY }}
         run: |
           # Only proceed if the robot was created or if it already existed
-          if grep -q "name=robot_id" $GITHUB_OUTPUT || grep -q "name=exists::true" $GITHUB_OUTPUT; then
-            # Extract the robot ID from the output JSON
-            ROBOT_ID=${{ secrets.ROBOCORP_ROBOT_ID }}
-            # Push the robot to Robocorp Control Room using the retrieved robot ID
-            rcc cloud push -d . -r $ROBOT_ID -w ${{ secrets.ROBOCORP_WORKSPACE_ID }}
-            # Capture the exit code of the previous command
-            EXIT_CODE=$?
-            # Provide feedback based on the exit code
-            if [ $EXIT_CODE -eq 0 ]; then
-              echo "Robocloud process completed successfully."
-            else
-              echo "Robocloud process failed with exit code $EXIT_CODE."
-              exit $EXIT_CODE
-            fi
+          # Extract the robot ID from the output JSON
+          ROBOT_ID=${{ secrets.ROBOCORP_ROBOT_ID }}
+          # Push the robot to Robocorp Control Room using the retrieved robot ID
+          rcc cloud push -d . -r $ROBOT_ID -w ${{ secrets.ROBOCORP_WORKSPACE_ID }}
+          # Capture the exit code of the previous command
+          EXIT_CODE=$?
+          # Provide feedback based on the exit code
+          if [ $EXIT_CODE -eq 0 ]; then
+            echo "Robocloud process completed successfully."
           else
-            echo "Failed to create or find the robot. Exiting..."
-            exit 1
+            echo "Robocloud process failed with exit code $EXIT_CODE."
+            exit $EXIT_CODE
           fi
